### ISSUE TITLE
Jaccard Randomization fails on comparison of stratification group

### ISSUE THREAD

**Issue by keckelt** [Caleydo/touring#5]
```
JaccardRandom.ts:40 Cannot calculate Jaccard p-value.    Error Type: Error    Message: You requested more unique numbers than can fit between 0 and -1. n=249
StackTrace: Error: You requested more unique numbers than can fit between 0 and -1. n=249
   at getRandomUniqueIntegers (http://localhost:8080/JaccardRandom.js:177:15)
   at ctx.onmessage (http://localhost:8080/JaccardRandom.js:1172:129)
```

**Comment by keckelt** [comment]
Did not Pass the Data to Draw random sets to the Measures lib.
